spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: p@ssw0rd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase.change-log: classpath:db/changelog/db-changelog.xml

#server:
#    contextPath: "liquibase"